import assert from 'node:assert/strict';
import {documentPackLine,purchaseDefaults} from '../app/purchase-defaults';
import {calculatePack} from '../app/purchase-packs';
const items=[{productId:'a',quantity:12,unitCost:98/12,piecesPerPack:12,packCost:98},{productId:'b',quantity:20,unitCost:9.6,piecesPerPack:10,packCost:96},{productId:'c',quantity:30,unitCost:95/15,piecesPerPack:15,packCost:95}];
const lines=items.map(i=>documentPackLine(i));
assert.deepEqual(lines.map(l=>[l.packCount,l.piecesPerPack,l.packCost]),[['1','12','98'],['2','10','96'],['2','15','95']]);
assert.equal(lines.reduce((n,l)=>n+calculatePack(l).total,0),480);
assert.equal(documentPackLine(items[1],10).packCount,'1');
assert.equal(calculatePack(documentPackLine(items[1],7)).quantity,7);
const product:any={id:'a',packSize:12,costPrice:7};
const order:any={id:'1',orderNo:'PO1',supplierId:'s',createdAt:'2026-09-01',status:'OPEN',items:[items[0]],taxMode:'none'};
const snapshot:any={purchaseOrders:[order],purchases:[]};
assert.equal(purchaseDefaults(product,snapshot,'s').packCost,'98');
assert.equal(purchaseDefaults(product,snapshot,'different').packCost,'84');
snapshot.purchaseOrders.push({...order,id:'2',orderNo:'PO2',createdAt:'2026-09-02',status:'CANCELLED',items:[{...items[0],packCost:999}]});
assert.equal(purchaseDefaults(product,snapshot,'s').source,'PO1');
snapshot.purchases.push({...order,id:'3',purchaseNo:'GR1',createdAt:'2026-08-01',updatedAt:'2026-09-03',items:[{...items[0],packCost:888}]});
assert.equal(purchaseDefaults(product,snapshot,'s').source,'PO1');
order.taxMode='exclusive';order.taxRate=7;
assert.equal(purchaseDefaults(product,snapshot,'s','inclusive',7).packCost,'104.86');
assert.equal(purchaseDefaults(product,snapshot,'s','exclusive',7).packCost,'98');
for(const value of ['','-1','1.5','abc'])assert.throws(()=>calculatePack({...lines[0],packCount:value}));
console.log('Pack continuity, partial quantities, remembered supplier prices, VAT basis and numeric validation passed');
