'use client';
import {useState} from 'react';
import Staff from './staff';
import * as api from './office-api';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export type ShopSettings={revision?:number;name:string;address:string;phone:string;taxId:string;branch:string;logoUrl:string;footer:string;taxMode:'none'|'inclusive'|'exclusive';taxRate:number};
export const defaultShop:ShopSettings={name:'ชุติมา FRESH LAUNDRY',address:'',phone:'',taxId:'',branch:'',logoUrl:'',footer:'',taxMode:'none',taxRate:0};
export default function OfficeSettings({data,refresh,onConnection}:{data:api.OfficeData;refresh:()=>void;onConnection:()=>void}){
 const [tab,setTab]=useState('shop'),[draft,setDraft]=useState<ShopSettings|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const saved={...defaultShop,...data.snapshot?.officeSettings},value=draft||saved,owner=api.currentRole()==='owner',supported=Number(data.snapshot?.purchaseWorkflowVersion)>=2;
 async function save(){if(busy)return;setBusy(true);setMessage('');try{await api.submit(crypto.randomUUID(),'purchase.receive',{workflow:'office.settings',expectedRevision:saved.revision||0,settings:value});setDraft(null);setMessage('ส่งการตั้งค่าแล้ว รอ SERVERJJ ยืนยัน');refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <div className="settings-workspace"><div className="purchasing-tabs">{[['shop','ข้อมูลร้านค้า'],['documents','เอกสารและ VAT'],...(owner?[['staff','พนักงานและสิทธิ์']]:[]),['connection','การเชื่อมต่อและสำรองข้อมูล']].map(([id,label])=><Button key={id} variant={tab===id?'default':'outline'} onClick={()=>setTab(id)}>{label}</Button>)}</div>{tab==='staff'?<Staff/>:tab==='connection'?<section><h2>การเชื่อมต่อระบบ</h2><p>SERVERJJ: {data.source==='serverjj'?'เชื่อมต่อแล้ว':'รอเชื่อมต่อ'} · ข้อมูลล่าสุด {data.snapshotAt?new Date(data.snapshotAt).toLocaleString('th-TH'):'—'}</p>{data.devices?.map(d=><p key={d.id}>{d.label} · {d.online?'ออนไลน์':'ออฟไลน์'} · ค้างส่ง {d.pending}</p>)}<Button variant="outline" onClick={onConnection}>ตั้งค่าการเชื่อมต่อเว็บ</Button><h3>สำรองข้อมูล</h3><p>สำรองข้อมูลบน SERVERJJ จัดการโดยบริการของเครื่องเซิร์ฟเวอร์ ส่วนสำรองใน POS จัดการจากเครื่องขายแต่ละเครื่อง</p><p>หน้าเว็บยังไม่รับข้อมูลวันที่สำรองล่าสุดจากเซิร์ฟเวอร์</p></section>:<section><h2>{tab==='shop'?'ข้อมูลร้านค้าสำหรับเอกสาร':'รูปแบบเอกสารและค่าเริ่มต้น VAT'}</h2><p>ใช้กับเอกสารบนเว็บ และเก็บค่าร่วมกันบน SERVERJJ</p>{!supported&&<p className="purchasing-note">บันทึกข้อมูลร้านและ VAT ได้หลังอัปเดตตัวเชื่อมเว็บ SERVERJJ 0.17.1</p>}<div className="form-grid">{tab==='shop'?(['name','address','phone','taxId','branch','logoUrl'] as const).map((key)=><label className="office-field" key={key}><span>{{name:'ชื่อร้านค้า',address:'ที่อยู่',phone:'เบอร์โทร',taxId:'เลขผู้เสียภาษี (ถ้ามี)',branch:'สำนักงานใหญ่ / สาขา',logoUrl:'ลิงก์โลโก้ HTTPS (เว้นว่างใช้โลโก้เดิม)'}[key]}</span><Input disabled={busy||!owner} value={value[key]} maxLength={key==='address'?1000:500} onChange={e=>setDraft({...value,[key]:e.target.value})}/></label>):<><label className="office-field"><span>VAT เริ่มต้น (เปลี่ยนได้ในแต่ละใบ)</span><select disabled={!owner} value={value.taxMode} onChange={e=>setDraft({...value,taxMode:e.target.value as ShopSettings['taxMode']})}><option value="none">ไม่มี VAT</option><option value="inclusive">รวม VAT</option><option value="exclusive">แยก VAT</option></select></label><label className="office-field"><span>อัตรา VAT (%)</span><Input type="number" min={0} max={100} disabled={!owner} value={value.taxRate} onChange={e=>setDraft({...value,taxRate:Number(e.target.value)})}/></label><label className="office-field"><span>ข้อความท้ายเอกสาร</span><Input disabled={!owner} value={value.footer} maxLength={1000} onChange={e=>setDraft({...value,footer:e.target.value})}/></label><p>ใบสั่งซื้อใช้ PO · ใบรับใหม่ใช้ GR · เอกสารเดิมคงเลขเดิมเพื่อค้นย้อนหลัง</p></>}</div><p className="form-help">ส่วนลดหักก่อน VAT และค่าขนส่งใช้อัตรา VAT เดียวกับเอกสาร ต้นทุนรับสินค้าใช้ยอดรวมที่จ่ายรวม VAT</p>{message&&<p role="status">{message}</p>}{owner&&<Button disabled={busy||!supported||!draft} onClick={()=>void save()}>{busy?'กำลังส่ง…':'บันทึกการตั้งค่า'}</Button>}</section>}</div>;
}
