'use client';
import {useRef,useState} from 'react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import * as api from './office-api';import type {Purchase} from './office-api';
export default function Settlement({purchase,mode,onClose,onSaved}:{purchase:Purchase;mode:'pay'|'return';onClose:()=>void;onSaved:()=>void}){
 const [amount,setAmount]=useState(''),[quantity,setQuantity]=useState(''),[productId,setProductId]=useState(''),[method,setMethod]=useState('qr'),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false),attempt=useRef<{fingerprint:string;id:string}|null>(null);
 async function save(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const value=Number(amount);if(!amount||!Number.isFinite(value)||value<0)throw Error('กรอกยอดเงินให้ถูกต้อง');if(mode==='pay'&&(!value||value>purchase.balance))throw Error('ยอดจ่ายต้องมากกว่า 0 และไม่เกินยอดค้าง');if(mode==='return'&&(!productId||!Number.isSafeInteger(Number(quantity))||Number(quantity)<1||!notes.trim()))throw Error('เลือกสินค้า จำนวนเต็มมากกว่า 0 และเหตุผลคืน');
 const payload={workflow:mode==='pay'?'purchase.pay':'purchase.return',purchaseId:purchase.id,expectedRevision:purchase.revision||0,...(mode==='pay'?{amount:value,paymentMethod:method}:{productId,quantity:Number(quantity),creditAmount:value}),notes};const fingerprint=JSON.stringify(payload);if(attempt.current?.fingerprint!==fingerprint)attempt.current={fingerprint,id:crypto.randomUUID()};await api.submit(attempt.current.id,'purchase.receive',payload);onSaved();onClose();
 }catch(e){setError((e as Error).message);}finally{setBusy(false);lock.current=false;}}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="office-dialog" showCloseButton={!busy}><DialogHeader><DialogTitle>{mode==='pay'?'บันทึกชำระหนี้':'คืนสินค้าให้ผู้จำหน่าย'}</DialogTitle><DialogDescription>{purchase.purchaseNo} · {purchase.supplierSnapshot.name}</DialogDescription></DialogHeader>
 {mode==='pay'?<p>ค้างชำระ {purchase.balance.toFixed(2)} บาท · บันทึกนี้ไม่หักเงินลิ้นชัก POS</p>:<><p className="purchasing-note">ระบบจะรอ POS ส่งยอดและพักจำนวนขายของสินค้านี้ก่อนคืน หากเครื่องออฟไลน์จะยังไม่ตัดสต๊อก</p><label className="office-field"><span>สินค้า</span><select value={productId} disabled={busy} onChange={e=>setProductId(e.target.value)}><option value="">เลือกสินค้า</option>{purchase.items.map((i,k)=><option value={i.productId} key={k}>{i.name} · รับเดิม {i.quantity} ชิ้น</option>)}</select></label><label className="office-field"><span>จำนวนคืน (ชิ้น)</span><Input type="number" min="1" step="1" disabled={busy} value={quantity} onChange={e=>{setQuantity(e.target.value);const i=purchase.items.find(i=>i.productId===productId);setAmount(String(Math.round(Number(e.target.value)*Number(i?.effectiveUnitCost??i?.unitCost??0)*100)/100));}}/></label></>}
 <label className="office-field"><span>{mode==='pay'?'จำนวนเงินที่จ่าย':'ยอดลดหนี้ที่ผู้จำหน่ายยอมรับ'}</span><Input type="number" min="0" step="0.01" disabled={busy} value={amount} onChange={e=>setAmount(e.target.value)}/></label>{mode==='pay'&&<label className="office-field"><span>ช่องทาง</span><select disabled={busy} value={method} onChange={e=>setMethod(e.target.value)}><option value="qr">โอน / QR</option><option value="cash">เงินสดนอกลิ้นชัก POS</option></select></label>}
 <label className="office-field"><span>หมายเหตุ / เหตุผล</span><Input disabled={busy} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<p className="office-error" role="alert">{error}</p>}<DialogFooter><Button variant="outline" disabled={busy} onClick={onClose}>ยกเลิก</Button><Button disabled={busy} onClick={()=>void save()}>{busy?'กำลังส่ง…':'ยืนยันบันทึก'}</Button></DialogFooter></DialogContent></Dialog>;
}
