import {defaultShop,type ShopSettings} from './office-settings';
import {taxLabels} from './document-totals';
import type {PurchaseOrder,Purchase} from './office-api';
export function printPurchaseDocument(value:PurchaseOrder|Purchase,settings?:Partial<ShopSettings>){
 const order='orderNo' in value&&'status' in value&&'supplierId' in value&&'received' in (value.items[0]||{}),v=value as PurchaseOrder&Purchase;
 const shop={...defaultShop,...settings,...v.shopSnapshot},frame=document.createElement('iframe');frame.title='เอกสารจัดซื้อสำหรับพิมพ์';frame.style.cssText='position:fixed;width:1px;height:1px;bottom:0;border:0';document.body.appendChild(frame);
 const doc=frame.contentDocument!;doc.open();doc.write('<!doctype html><html lang="th"><head><meta charset="utf-8"><style>@page{size:A4 portrait;margin:14mm}body{font:12px Tahoma,Arial,sans-serif;color:#222}header{display:flex;justify-content:space-between;border-bottom:2px solid #333;padding-bottom:16px}img{width:64px;height:64px;object-fit:contain;float:left;margin-right:12px}h1{font-size:22px}h2{font-size:16px;margin:0 0 8px}p{white-space:pre-wrap;line-height:1.7}table{width:100%;border-collapse:collapse;margin:20px 0}th,td{padding:8px 5px;border:1px solid #bbb;text-align:right}th:nth-child(2),td:nth-child(2){text-align:left}thead{display:table-header-group}tr{break-inside:avoid}.totals{margin-left:auto;width:55%}.signatures{display:flex;justify-content:space-around;margin-top:65px}.signatures p{border-top:1px solid #555;padding:12px 24px;text-align:center}</style><title></title></head><body></body></html>');doc.close();
 const text=(tag:string,s:string,parent:HTMLElement=doc.body)=>{const e=doc.createElement(tag);e.textContent=s;parent.appendChild(e);return e;},fmt=(n:number)=>Number(n||0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
 const no=order?v.orderNo:v.purchaseNo;doc.title=no;const head=doc.createElement('header');doc.body.appendChild(head);const left=doc.createElement('div');head.appendChild(left);const img=doc.createElement('img');img.src=shop.logoUrl&&/^https:\/\//.test(shop.logoUrl)?shop.logoUrl:new URL('./logo.jpg',location.href).href;left.appendChild(img);text('h2',shop.name,left);text('p',[shop.address,shop.phone&&'โทร. '+shop.phone,shop.taxId&&'เลขผู้เสียภาษี '+shop.taxId,shop.branch].filter(Boolean).join('\n'),left);text('h1',order?'ใบสั่งซื้อ':'ใบรับสินค้า',head);
 text('p',`เลขที่ ${no}${v.status==='CANCELLED'?' · ยกเลิกแล้ว':''}\nวันที่ ${new Date(v.createdAt).toLocaleDateString('th-TH')}\nผู้จำหน่าย ${order?v.supplierName:v.supplierSnapshot?.name||''}${!order&&v.orderNo?'\nอ้างอิงใบสั่งซื้อ '+v.orderNo:''}${v.documentNo?'\nเอกสารผู้จำหน่าย '+v.documentNo:''}${v.expectedDate?'\nกำหนดรับ '+v.expectedDate:''}`);
 const table=doc.createElement('table');doc.body.appendChild(table);const headers=order?['ลำดับ','รหัส / สินค้า','สั่ง (ชิ้น)','รับสะสม','ค้างรับ','ราคา/ชิ้น','รวม']:['ลำดับ','รหัส / สินค้า','จำนวน (ชิ้น)','ราคา/ชิ้น','รวม'];const tr=table.createTHead().insertRow();headers.forEach(x=>text('th',x,tr));const body=table.createTBody();v.items.forEach((i,n)=>{const r=body.insertRow();const a=order?[n+1,(i.sku||'')+' '+i.name,i.quantity,i.received,Math.max(0,i.quantity-i.received),fmt(i.unitCost),fmt(i.quantity*i.unitCost)]:[n+1,(i.sku||'')+' '+i.name,i.quantity,fmt(i.unitCost),fmt(i.quantity*i.unitCost)];a.forEach(x=>text('td',String(x),r));if(i.piecesPerPack&&i.piecesPerPack>1){const sub=body.insertRow().insertCell();sub.colSpan=headers.length;sub.textContent=`${i.packCount} แพ็ก × ${i.piecesPerPack} ชิ้น/แพ็ก · ${fmt(i.packCost||0)} บาท/แพ็ก`;}});
 const totals=text('div','');totals.className='totals';for(const [label,n] of [['ยอดสินค้า',v.subtotal??v.items.reduce((n,i)=>n+i.quantity*i.unitCost,0)],['ส่วนลด',v.discount||0],['ค่าขนส่ง',v.shipping||0],['ฐานก่อน VAT',v.taxableAmount??v.total],[`${taxLabels[v.taxMode||'none']} ${v.taxRate||0}%`,v.taxAmount||0],['ยอดสุทธิ',v.total],...(!order?[['ชำระแล้ว',v.paidAmount],['ค้างชำระ',v.balance]]:[])] as [string,number][])text('p',`${label}     ${fmt(n)} บาท`,totals);
 text('p',[v.notes,shop.footer].filter(Boolean).join('\n'));const sig=text('div','');sig.className='signatures';(order?['ผู้จัดทำ / ผู้สั่งซื้อ','ผู้อนุมัติ']:['ผู้ส่งสินค้า','ผู้รับสินค้า','ผู้ตรวจสอบ']).forEach(s=>text('p',s+'\nวันที่ ………………',sig));
 let printed=false;const show=()=>{if(printed)return;printed=true;frame.contentWindow?.focus();frame.contentWindow?.print();setTimeout(()=>frame.remove(),60000);};img.onload=()=>setTimeout(show,100);img.onerror=()=>setTimeout(show,100);if(img.complete)setTimeout(show,100);
}
