import {defaultShop,type ShopSettings} from './office-settings';
import {taxLabels} from './document-totals';
import type {PurchaseOrder,Purchase,Supplier} from './office-api';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(n:unknown)=>Number(n||0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
const date=(v:unknown)=>v?new Date(String(v)).toLocaleDateString('th-TH'):'-';
export function purchaseDocumentHtml(value:PurchaseOrder|Purchase,settings?:Partial<ShopSettings>,supplier?:Supplier,logoUrl=''){
 const order='supplierName' in value,v=value as PurchaseOrder&Purchase;
 const shop={...defaultShop,...settings,...v.shopSnapshot};
 // Preserve historical details; fill only previously missing supplier fields.
 const vendor={...supplier,...Object.fromEntries(Object.entries(v.supplierSnapshot||{}).filter(([,x])=>x!==undefined&&x!==null&&x!==''))};
 const no=order?v.orderNo:v.purchaseNo,title=order?'ใบสั่งซื้อ':'ใบรับสินค้าเข้า';
 const logo=shop.logoUrl&&/^https:\/\//.test(shop.logoUrl)?shop.logoUrl:logoUrl;
 const pages:typeof v.items[]=[];let current:typeof v.items=[],weight=0;
 for(const item of v.items){const w=Math.max(1,Math.ceil(item.name.length/30))+(item.piecesPerPack&&item.piecesPerPack>1?0.5:0);if(current.length&&weight+w>18){pages.push(current);current=[];weight=0;}current.push(item);weight+=w;}if(current.length||!pages.length)pages.push(current);
 const field=(label:string,val:unknown)=>`<div class="field"><b>${esc(label)}</b><span>${esc(val||'-')}</span></div>`;
 let index=0;
 const html=pages.map((items,page)=>{
 const last=page===pages.length-1;
 const rows=items.map(i=>{const packed=!!i.piecesPerPack&&i.piecesPerPack>1&&i.quantity%i.piecesPerPack===0;const count=packed?i.quantity/i.piecesPerPack!:i.quantity,price=packed?(i.packCost??i.unitCost*i.piecesPerPack!):i.unitCost;
 return `<tr><td class="center">${++index}</td><td>${esc(i.sku||'-')}</td><td>${esc(i.name)}${packed?`<small>${i.piecesPerPack} ชิ้น/แพ็ก · รวม ${i.quantity} ชิ้น</small>`:''}</td><td class="number">${count.toLocaleString('th-TH')}</td><td class="center">${packed?'แพ็ก':'ชิ้น'}</td><td class="number">${money(price)}</td><td class="number">${money(i.quantity*i.unitCost)}</td></tr>`;}).join('');
 const totalRows:[string,unknown][]=[['รวมเงินสินค้า',v.subtotal??v.items.reduce((n,i)=>n+i.quantity*i.unitCost,0)],['ส่วนลด',v.discount],['ค่าขนส่ง',v.shipping],['มูลค่าก่อน VAT',v.taxableAmount??v.total],[v.taxMode==='none'||!v.taxMode?'ไม่มี VAT':`${taxLabels[v.taxMode]} ${v.taxRate||0}%`,v.taxAmount],['จำนวนเงินทั้งสิ้น',v.total]];
 return `<section class="page"><div class="page-no">หน้า ${page+1} / ${pages.length}</div><header>${logo?`<img src="${esc(logo)}" alt="">`:''}<div><h2>${esc(shop.name)}</h2><p>${esc(shop.address||'')}</p><p>${esc([shop.phone&&'โทร. '+shop.phone,shop.taxId&&'เลขประจำตัวผู้เสียภาษี '+shop.taxId].filter(Boolean).join(' · '))}</p><p>${esc(shop.branch||'')}</p></div></header><h1>${title}${v.status==='CANCELLED'?' (ยกเลิก)':''}</h1><div class="info"><div class="box">${field('รหัสผู้จำหน่าย',vendor.code)}${field('ผู้จำหน่าย',vendor.name||v.supplierName)}${field('ที่อยู่',vendor.address)}${field('เลขผู้เสียภาษี',vendor.taxId)}${field('ผู้ติดต่อ / โทร.',[vendor.contactName,vendor.phone].filter(Boolean).join(' / '))}</div><div class="box">${field('เลขที่เอกสาร',no)}${field('วันที่เอกสาร',date(v.createdAt))}${field(order?'กำหนดรับสินค้า':'อ้างอิงใบสั่งซื้อ',order?date(v.expectedDate):v.orderNo)}${field('เอกสารผู้จำหน่าย',v.documentNo)}${field('กำหนดชำระ',date(v.dueDate))}</div></div><table class="items"><colgroup><col style="width:7%"><col style="width:15%"><col style="width:30%"><col style="width:10%"><col style="width:9%"><col style="width:14%"><col style="width:15%"></colgroup><thead><tr>${['ลำดับ','รหัสสินค้า','รายการ','จำนวน','หน่วย','ราคา/หน่วย','จำนวนเงิน'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table>${last?`<div class="closing"><div class="notes"><b>หมายเหตุ</b><p>${esc(v.notes||'-')}</p>${shop.footer?`<p>${esc(shop.footer)}</p>`:''}${!order?`<p>ชำระแล้ว ${money(v.paidAmount)} บาท<br>ค้างชำระ ${money(v.balance)} บาท</p>`:''}</div><table class="totals">${totalRows.map(([label,n],i)=>`<tr${i===totalRows.length-1?' class="grand"':''}><th>${esc(label)}</th><td>${money(n)}</td></tr>`).join('')}</table></div><div class="signatures">${(order?['ผู้จัดทำ / ผู้สั่งซื้อ','ผู้ตรวจสอบ','ผู้อนุมัติ']:['ผู้ส่งสินค้า','ผู้รับสินค้า','ผู้ตรวจสอบ','ผู้อนุมัติ']).map(s=>`<div><div class="sign-line"></div><b>${s}</b><p>วันที่ ......... / ......... / .........</p></div>`).join('')}</div>`:'<div class="continued">มีรายการต่อหน้าถัดไป</div>'}</section>`;
 }).join('');
 return `<!doctype html><html lang="th"><head><meta charset="utf-8"><title>${esc(no)}</title><style>
 @page{size:A4 portrait;margin:10mm}*{box-sizing:border-box}body{margin:0;color:#111;font:12px Tahoma,Arial,sans-serif;background:#fff}.page{width:190mm;height:276mm;display:flex;flex-direction:column;break-after:page;position:relative}.page:last-child{break-after:auto}.page-no{text-align:right;font-size:10px;height:5mm}header{display:flex;align-items:center;justify-content:flex-start;gap:4mm;min-height:23mm}header img{width:23mm;height:23mm;object-fit:contain}header div{text-align:left;flex:1}h2{font-size:20px;margin:0 0 1mm}p{margin:1mm 0;white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.55}h1{text-align:center;font-size:23px;margin:4mm 0}.info{display:grid;grid-template-columns:1.1fr 1fr;gap:2mm;margin-bottom:3mm}.box{border:1px solid #333;border-radius:2mm;padding:3mm}.field{display:grid;grid-template-columns:29mm 1fr;gap:2mm;line-height:1.6;padding:.6mm 0}.field span{white-space:pre-wrap;overflow-wrap:anywhere}table{border-collapse:collapse;width:100%;table-layout:fixed}.items{flex:none;margin-bottom:3mm}.items th,.items td{border:0;padding:.5mm 1.6mm;vertical-align:top;overflow-wrap:anywhere}.items th{background:#f2f3f5;text-align:center;border-bottom:1px solid #777;padding:1.5mm 1.6mm}.items tbody tr{break-inside:avoid;line-height:1.15}.items small{display:block;font-size:10px;margin-top:0;color:#444}.number{text-align:right;white-space:nowrap}.center{text-align:center}.closing{display:grid;grid-template-columns:1.15fr 1fr;border:1px solid #777;break-inside:avoid}.notes{padding:3mm;overflow-wrap:anywhere}.totals th,.totals td{border-left:1px solid #777;border-bottom:1px solid #aaa;padding:1.2mm 2mm;font-weight:normal}.totals th{text-align:left;width:65%}.totals td{text-align:right;white-space:nowrap}.totals tr:last-child>*{border-bottom:0}.totals .grand>*{font-weight:bold;background:#f2f3f5;font-size:13px}.signatures{display:flex;border:1px solid #777;margin-top:3mm;min-height:29mm;break-inside:avoid}.signatures>div{flex:1;text-align:center;padding:3mm 2mm;border-right:1px solid #777;font-size:11px}.signatures>div:last-child{border:0}.sign-line{height:10mm;border-bottom:1px solid #555;margin:0 3mm 2mm}.continued{text-align:right;padding:3mm;font-size:11px}@media screen{body{background:#ddd;padding:12px}.page{background:white;margin:0 auto 12px;padding:0;box-shadow:0 1px 4px #999}}
 </style></head><body>${html}</body></html>`;
}
export function printPurchaseDocument(value:PurchaseOrder|Purchase,settings?:Partial<ShopSettings>,supplier?:Supplier){
 const frame=document.createElement('iframe');frame.title='เอกสารจัดซื้อสำหรับพิมพ์';frame.style.cssText='position:fixed;width:1px;height:1px;bottom:0;border:0';document.body.appendChild(frame);
 const doc=frame.contentDocument!;doc.open();doc.write(purchaseDocumentHtml(value,settings,supplier,new URL('./logo.jpg',location.href).href));doc.close();
 const images=Array.from(doc.images);Promise.all(images.map(img=>img.complete?Promise.resolve():new Promise<void>(resolve=>{img.onload=()=>resolve();img.onerror=()=>resolve();setTimeout(resolve,3000);}))).then(()=>{frame.contentWindow?.focus();frame.contentWindow?.print();setTimeout(()=>frame.remove(),60000);});
}
