'use client';
import {useRef,useState} from 'react';
import * as api from './office-api';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Draft=Omit<api.VendingMachine,'items'>&{items:(Omit<api.VendingMachine['items'][number],'price'>&{price:number|string})[]};
export default function VendingSettings({data,refresh}:{data:api.OfficeData;refresh:()=>void}){
 const [draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const lock=useRef(false);
 const machines=data.snapshot?.vendingMachines||[],products=data.snapshot?.products||[],supported=(data.snapshot?.vendingWorkflowVersion||0)>=1;
 function toggle(productId:string,checked:boolean){if(!draft)return;const p=products.find(p=>p.id===productId)!;setDraft({...draft,items:checked?[...draft.items,{productId,name:p.name,unit:p.unit,stock:0,price:p.price,queueDefault:false}]:draft.items.filter(i=>i.productId!==productId)});}
 async function save(){if(!draft||lock.current)return;lock.current=true;setBusy(true);setMessage('');try{if(!draft.name.trim())throw Error('กรุณาตั้งชื่อตู้');for(const i of draft.items)if(!/^\d+(?:\.\d{1,2})?$/.test(String(i.price))||!Number.isFinite(Number(i.price))||Number(i.price)<0)throw Error('ราคาหยอดต้องเป็นตัวเลขตั้งแต่ 0');await api.submit(crypto.randomUUID(),'purchase.receive',{workflow:'vending.machine.save',machineId:draft.id||undefined,name:draft.name,active:draft.active,expectedRevision:draft.revision,items:draft.items.map(i=>({productId:i.productId,price:Number(i.price),queueDefault:i.queueDefault}))});setDraft(null);setMessage('ส่งการตั้งค่าตู้แล้ว รอ SERVERJJ ยืนยัน');refresh();}catch(e){setMessage((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 return <section><div className="purchase-actions"><div><h2>ตู้ขายสินค้า</h2><p>เลือกว่าสินค้าใดอยู่ตู้ไหน และกำหนดตู้ประจำสำหรับหน้าเพิ่มคิว</p></div><Button disabled={!supported} onClick={()=>setDraft({id:'',name:'',active:true,revision:0,cashBalance:0,items:[]})}>＋ เพิ่มตู้</Button></div>{!supported&&<p className="office-notice">ใช้การตั้งค่าตู้ได้หลังอัปเดต SERVERJJ 0.20.0</p>}{message&&<p className="office-notice" role="status">{message}</p>}<div className="form-grid">{machines.map(m=><section className="purchase-line-card" key={m.id}><h3>{m.name}</h3><p>{m.active?'เปิดใช้งาน':'ปิดใช้งาน'}</p>{m.items.map(i=><p key={i.productId}>{i.name} · {i.price.toFixed(2)} บาท / {i.unit} · เหลือ {i.stock} {i.queueDefault&&<strong> · ตู้ประจำหน้าเพิ่มคิว</strong>}</p>)}<Button variant="outline" onClick={()=>setDraft(structuredClone(m))}>แก้ไขตู้ / สินค้า</Button></section>)}</div><Dialog open={!!draft} onOpenChange={open=>{if(!open&&!busy)setDraft(null);}}><DialogContent className="office-dialog"><DialogHeader><DialogTitle>{draft?.id?'แก้ไขตู้':'เพิ่มตู้ขายสินค้า'}</DialogTitle><DialogDescription>หนึ่งตู้มีสินค้าหลายชนิดได้ และสินค้าเดียวกันอยู่หลายตู้ได้ ตู้ประจำช่วยเลือกให้ตอนเพิ่มคิว</DialogDescription></DialogHeader>{draft&&<><label className="office-field"><span>ชื่อตู้</span><Input disabled={busy} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><div className="vending-product-list">{products.filter(p=>p.enabled||draft.items.some(i=>i.productId===p.id)).map(p=>{const item=draft.items.find(i=>i.productId===p.id);return <section className="purchase-line-card" key={p.id}><label><input disabled={busy} type="checkbox" checked={!!item} onChange={e=>toggle(p.id,e.target.checked)}/> ขาย {p.name} ในตู้นี้</label>{item&&<div className="form-grid"><label className="office-field"><span>ราคาหยอดต่อ {p.unit}</span><Input disabled={busy} type="text" inputMode="decimal" value={item.price} onChange={e=>setDraft({...draft,items:draft.items.map(i=>i.productId===p.id?{...i,price:e.target.value}:i)})}/></label><label><input disabled={busy} type="checkbox" checked={!!item.queueDefault} onChange={e=>setDraft({...draft,items:draft.items.map(i=>i.productId===p.id?{...i,queueDefault:e.target.checked}:i)})}/> ใช้เป็นตู้ประจำในหน้าเพิ่มคิว</label></div>}</section>;})}</div><label><input disabled={busy} type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/> เปิดใช้งานตู้</label>{message&&<p role="alert">{message}</p>}<Button disabled={busy} onClick={()=>void save()}>{busy?'กำลังส่ง…':'บันทึกตู้'}</Button></>}</DialogContent></Dialog></section>;
}
